# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://127.0.0.1:8080/customers/513b027f-d5b0-450c-8ede-a74641af5334
Accept: application/json

###

POST http://127.0.0.1:8080/customers
Content-Type: application/json

{
    "name": "Balrok"
}

###
